export const REQUEST_CREATE_TASK = 'REQUEST_CREATE_TASK';
export const RECEIVE_CREATE_TASK = 'RECEIVE_CREATE_TASK';
export const REQUEST_UPDATE_TASK = 'REQUEST_UPDATE_TASK';
export const RECEIVE_UPDATE_TASK = 'RECEIVE_UPDATE_TASK';
export const REQUEST_TASKS = 'REQUEST_TASKS';
export const RECEIVE_TASKS = 'RECEIVE_TASKS';
