export const ADD_TASK = 'ADD_TASK';
export const REQUEST_UPDATE_TASK = 'REQUEST_UPDATE_TASK';
export const RECEIVE_UPDATE_TASK = 'RECEIVE_UPDATE_TASK';
export const REQUEST_TASKS = 'REQUEST_TASKS';
export const RECEIVE_TASKS = 'RECEIVE_TASKS';
