export const REQUEST_TASK_CREATE = 'REQUEST_TASK_CREATE';
export const RECEIVE_TASK_CREATE = 'RECEIVE_TASK_CREATE';
export const REQUEST_TASK_UPDATE = 'REQUEST_TASK_UPDATE';
export const RECEIVE_TASK_UPDATE = 'RECEIVE_TASK_UPDATE';
export const REQUEST_TASKS = 'REQUEST_TASKS';
export const RECEIVE_TASKS = 'RECEIVE_TASKS';
export const REQUEST_TASK_DELETE = 'REQUEST_TASK_DELETE';
export const RECEIVE_TASK_DELETE = 'RECEIVE_TASK_DELETE';
